### ISSUE TITLE
Add 'runtime' dependencies

### ISSUE THREAD

**Issue by smira** [talos-systems/bldr#30]
Proposal: add `runtime` flag to `stage:`:

```yaml

dependencies:
   - stage: m4
   - stage perl:
     runtime: yes
```

By default, all the dependencies are 'build' dependencies, i.e. they're pulled for the build. If dependency is marked as `runtime`, then if one stage is pulled in as a dependency, all of its runtime dependencies are pulled in as well.

Examples: `automake` requires `perl` (and `m4` iirc). So if `automake` is pulled in as build dependency, it should always pull `perl` and `m4`, as `automake` doesn't run without it.
